## Arrays

### YouTrys!

We have already talked about lists in SageMath/Python.   Lists are great but are also general:   lists are designed to be able to cope with any sort of data but that also means they don't have some of the specific functionality we might like to be able to analyse numerical data sets.   Arrays provide a way of representing and manipulating numerical data known an a matrix in maths lingo.  Matrices are particularly useful for data science.

The lists we have been dealing with were one-dimensional.  An array and the matrix it represents in a computer can be multidimensional.   The most common forms of array that we will meet are one-dimensional and two-dimensional.   You can imagine a two-dimensional array as a grid, which has rows and columns.   Take for instance a 3-by-6 array (i.e., 3 rows and 6 columns).

<table border="1"><colgroup> <col width="20" /> <col width="30" /> <col width="20" /> <col width="30" /> <col width="20" /> <col width="30" /> </colgroup>
<tbody>
<tr>
<td>0</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
</tr>
<tr>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
<td>10</td>
<td>11</td>
</tr>
<tr>
<td>12</td>
<td>13</td>
<td>14</td>
<td>15</td>
<td>16</td>
<td>17</td>
</tr>
</tbody>
</table>

The array type is not available in the basic SageMath package, so we import a library package called numpy which includes arrays.

In [96]:
import numpy as np

# this is just to print
print ('numpy is imported')

numpy is imported


Because the arrays are part of numpy, not the basic SageMath package, we don't just say `array`, but instead qualify `array` with the name of the module it is in.  So, we say `np.array` since we did `import numpy as np`.

The cell below makes a two-dimensional 3-by-6 (3 rows by 6 columns) array by specifying the rows, and each element in each row, individually.

In [98]:
# make an array the hard way
array1 = np.array([[0,1,2,3,4,5],[6,7,8,9,10,11],[12,13,14,15,16,17]]) 
array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

We can use the `array`'s `shape` method to find out its **shape**. The shape method for a two-dimensional array returns an ordered pair in the form `(rows,columns)`.   In this case it tells us that we have 3 rows and 6 columns.

In [99]:
array1.shape

(3, 6)

Another way to make an `array` is to start with a one-dimensional array and `resize` it to give the `shape` we want, as we do in the two cells below.

We start by making a one-dimensional array using the `range` function we have met earlier.

In [100]:
array2 = np.array([int(i) for i in range(18)])     # make an one dimensional array of Python int's
array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

The array's `resize` allows us to specify a new shape for the same array. We are going to make a two-dimensional array with 3 rows and 6 columns.   Note that the shape you specify must be compatible with the number of elements in the array.   

In this case, `array2` has 18 elements and we specify a new shape of 3 rows and 6 columns, which still makes 18 = 3*6 elements.   

If the new shape you specify won't work with the array, you'll get an error message.

In [101]:
array2.resize(3,6)      # use the array's resize method to change the shape of the array 18=3*6
array2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

If you check the type for `array2`, you might be surprised to find that it is a `numpy.ndarray`.   What happened to `numpy.array`?   The array we are using is the NumPy N-dimensional array, or `numpy.ndarray`.

In [102]:
type(array2)

<class 'numpy.ndarray'>

Tensors and general multidimensional arrays are possible via `resize` method.

In [103]:
array2.resize(3,2,3)      # use the array's resize method to change the shape of the array 18=3*2*3
array2

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

The `range` function will only give us ranges of integers.   The numpy module includes a more flexible function `arange` (that's `arange` with one `r` -- think of it as something like a-for-array-range -- not 'arrange' with two r's).   The `arange` function takes parameters specifying the `start_argument`, `stop_argument` and `step_argument` values (similar to `range`), but is not restricted to integers and returns a one-dimensional array rather than a list.

Here we use `arange` to make an array of numbers from `0.0` (`start_argument`) going up in steps of `0.1` (`step_argument`) to `0.18` - `0.1` and just as with range, the last number we get in the array is `stop_argument - step_argument` = `0.18` - `0.01` = `0.17`.

In [104]:
array3 = np.arange(0.0,0.18,0.01)   # the pylab.arange(start, stop, step)
array3

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17])

In [105]:
type(array3) # type is actually a numpy.ndarray

<class 'numpy.ndarray'>

In [106]:
array3.shape # the shape is 1 dimensional

(18,)

### Resize and Reshape

The `resize` method resizes the array it is applied to.   

The `reshape` method will leave the original array unchanged but return a new array, based on the original one, of the required new shape.

In [107]:
array3.resize(9,2)                     # which we can resize into a 9 by 2 array
array3

array([[0.  , 0.01],
       [0.02, 0.03],
       [0.04, 0.05],
       [0.06, 0.07],
       [0.08, 0.09],
       [0.1 , 0.11],
       [0.12, 0.13],
       [0.14, 0.15],
       [0.16, 0.17]])

In [108]:
array3.shape                            # try to see the shape of array3 now

(9, 2)

In [109]:
array4 = array3.reshape(6,3)     # reshape makes a new array of the specified size 6 by 3
array4

array([[0.  , 0.01, 0.02],
       [0.03, 0.04, 0.05],
       [0.06, 0.07, 0.08],
       [0.09, 0.1 , 0.11],
       [0.12, 0.13, 0.14],
       [0.15, 0.16, 0.17]])

In [110]:
array4.shape                            # try to see the shape of array4 now

(6, 3)

In [111]:
array3.shape                            # try to see the shape of array3 now, i.e. after it was reshaped into array4

(9, 2)

So the reshape does leave the original array unchanged.

### Arrays: indexing, slicing and copying

Remember indexing into lists to find the elements at particular positions?   We can do this with arrays, but we need to specify the index we want for each dimension of the array.   For our two-dimensional arrays, we need to specify the row and column index, i.e. use a format like [`row_index`,`column_index`].  For exampe,  [0,0] gives us the element in the first column of the first row (as with lists, array indices start from 0 for the first element).

In [112]:
array4 = np.arange(0.0, 0.18, 0.01)   # make sure we have array4
array4.resize(6,3)     

array4

array([[0.  , 0.01, 0.02],
       [0.03, 0.04, 0.05],
       [0.06, 0.07, 0.08],
       [0.09, 0.1 , 0.11],
       [0.12, 0.13, 0.14],
       [0.15, 0.16, 0.17]])

`array4[0,0]` gives the element in the first row and first column while `array4[5,2]` gives us the element in the third column (index 2) of the sixth row (index 5).

In [113]:
array4[0,0]

0.0

In [114]:
array4[5,2]

0.17

We can use the colon to specify a range of columns or rows.  For example,  `[0:4,0]` gives us the elements in the first column (index 0) of rows with indices from 0 through 3.   Note that the row index range `0:4` gives rows with indices starting from index 0 and ending at index `3=4-1`, i.e., indices `0` through `3`.

In [115]:
array4[0:4,0]

array([0.  , 0.03, 0.06, 0.09])

Similarly we could get all the elements in the second column (column index 1) of rows with indices 2 through 4.

In [116]:
array4[2:5,1]

array([0.07, 0.1 , 0.13])

The colon on its own gives everything, so a column index of `:` gives all the columns.   Thus we can get, for example, all elements of a particular row  --  in this case, the third row.

In [117]:
array4[2,:]

array([0.06, 0.07, 0.08])

Or all the elements of a specified column, in this case the first column.

In [118]:
array4[:,0]

array([0.  , 0.03, 0.06, 0.09, 0.12, 0.15])

Or all the elements of a range of rows (think of this as like slicing the array horizontally to obtain row indices 1 through 4=5-1).

In [119]:
array4[1:5,:]

array([[0.03, 0.04, 0.05],
       [0.06, 0.07, 0.08],
       [0.09, 0.1 , 0.11],
       [0.12, 0.13, 0.14]])

Or all the elements of a range of columns (think of this as slicing the array vertically to obtain column indices 1 through 2).

In [120]:
array4[:,1:3]

array([[0.01, 0.02],
       [0.04, 0.05],
       [0.07, 0.08],
       [0.1 , 0.11],
       [0.13, 0.14],
       [0.16, 0.17]])

Naturally, we can slice both horizontally and vertically to obtain row indices 2 through 4 and column indices 0 through 1, as follows:

In [121]:
array4[2:5,0:2]     

array([[0.06, 0.07],
       [0.09, 0.1 ],
       [0.12, 0.13]])

Finally, `[:]` gives a copy of the whole array.  This copy of the original array can be assigned to a new name for furter manipulation without affecting the original array.

In [122]:
CopyOfArray4 = array4[:]         # assign a copy of array4 to the new array named CopyOfArray4
CopyOfArray4                     # disclose CopyOfArray4


array([[0.  , 0.01, 0.02],
       [0.03, 0.04, 0.05],
       [0.06, 0.07, 0.08],
       [0.09, 0.1 , 0.11],
       [0.12, 0.13, 0.14],
       [0.15, 0.16, 0.17]])

In [123]:
CopyOfArray4.resize(9,2) # resize CopyOfArray4 from a 6-by-3 array to a 9-by-2 array
CopyOfArray4             # disclose CopyOfArray4 as it is now

array([[0.  , 0.01],
       [0.02, 0.03],
       [0.04, 0.05],
       [0.06, 0.07],
       [0.08, 0.09],
       [0.1 , 0.11],
       [0.12, 0.13],
       [0.14, 0.15],
       [0.16, 0.17]])

In [124]:
array4             # note that our original array4 has remained unchanged with size 6-by-3

array([[0.  , 0.01, 0.02],
       [0.03, 0.04, 0.05],
       [0.06, 0.07, 0.08],
       [0.09, 0.1 , 0.11],
       [0.12, 0.13, 0.14],
       [0.15, 0.16, 0.17]])

### Useful arrays

NumPy provides quick ways of making some useful kinds of arrays.   Some of these are shown in the cells below.

An array of zeros or ones of a particular shape.   Here we ask for shape (2,3), i.e., 2 rows and 3 columns.

In [125]:
arrayOfZeros = np.zeros((2,3)) # get a 2-by-3 array of zeros
arrayOfZeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [126]:
arrayOfOnes = np.ones((2,3)) # get a 2-by-3 array of ones
arrayOfOnes

array([[1., 1., 1.],
       [1., 1., 1.]])

An array for the identity matrix, i.e., square (same number of elements on each dimension) matrix with 1's along the diagonal and 0's everywhere else.

In [127]:
iden = np.identity(3) # get a 3-by-3 identity matrix with 1's along the diagonal and 0's elsewhere
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Useful functions for sequences

Now we are going to demonstrate some useful methods of sequences.  A `list` is a sequence, and so is a `tuple`.  

There are differences between them (recall that tuples are immutable) but in many cases we can use the same methods on them because they are both sequences.  

We will demonstrate with a list and a tuple containing the same data values. The data could be the results of three IID Bernoulli trials..

In [128]:
obsDataList = [0, 1, 1]
obsDataList

[0, 1, 1]

In [129]:
obsDataTuple = tuple(obsDataList)
obsDataTuple

(0, 1, 1)

A useful operation we can perform on a tuple is to count the number of times a particular element, say 0 or 1 in our ObsDataTuple, occurs. This is a statistic of our data called the sample frequency of the element of interest.

In [130]:
obsDataTuple.count(0)        # frequency of 0 using the tuple

1

In [131]:
obsDataList.count(1)        # frequency of 1 using the list

2

Another useful operation we can perform on a tuple is to sum all elements in our `obsDataTuple` or further scale the sum by the sample size. These are also statistics of our data called the sample sum and the sample mean, respectively.   Try the same things with `obsDataList`. 

In [132]:
sum(obsDataTuple)            # sample sum

2

In [133]:
sum(obsDataTuple)/3          # sample mean using sage.rings.Rational

2/3

In [134]:
obsDataTuple.count(1) / 3    # alternative expression for sample mean in IID Bernoulli trials

2/3

We used a lot of the techniques we have seen so far when we wanted to get the relative frequency associated with each ball in the lotto data.

Let's revist the code that made relative frequencies and fully understand each part of it now.

In [135]:
ballOneFreqs = makeFreqDict(listBallOne)   # call the function to make the dictionary
totalCounts = sum(ballOneFreqs.values())
relFreqs = []
for k in ballOneFreqs.keys():
    relFreqs.append(k/totalCounts)
numRelFreqPairs = zip(ballOneFreqs.keys(), relFreqs) # zip the keys and relative frequencies together
print(list(numRelFreqPairs))

[(4, 2/557), (3, 3/1114), (11, 11/1114), (35, 35/1114), (23, 23/1114), (12, 6/557), (14, 7/557), (13, 13/1114), (15, 15/1114), (19, 19/1114), (36, 18/557), (18, 9/557), (37, 37/1114), (39, 39/1114), (1, 1/1114), (24, 12/557), (29, 29/1114), (38, 19/557), (40, 20/557), (7, 7/1114), (21, 21/1114), (32, 16/557), (2, 1/557), (34, 17/557), (20, 10/557), (28, 14/557), (30, 15/557), (9, 9/1114), (22, 11/557), (31, 31/1114), (16, 8/557), (5, 5/1114), (6, 3/557), (27, 27/1114), (10, 5/557), (25, 25/1114), (17, 17/1114), (26, 13/557), (33, 33/1114), (8, 4/557)]


We could also do it with a list comprehension as follows:

In [136]:
ballOneFreqs = makeFreqDict(listBallOne)   # call the function to make the dictionary
totalCounts = sum(ballOneFreqs.values())
relFreqs = [k/totalCounts for k in ballOneFreqs.keys()]
numRelFreqPairs = zip(ballOneFreqs.keys(), relFreqs) # zip the keys and relative frequencies together
print(list(numRelFreqPairs))

[(4, 2/557), (3, 3/1114), (11, 11/1114), (35, 35/1114), (23, 23/1114), (12, 6/557), (14, 7/557), (13, 13/1114), (15, 15/1114), (19, 19/1114), (36, 18/557), (18, 9/557), (37, 37/1114), (39, 39/1114), (1, 1/1114), (24, 12/557), (29, 29/1114), (38, 19/557), (40, 20/557), (7, 7/1114), (21, 21/1114), (32, 16/557), (2, 1/557), (34, 17/557), (20, 10/557), (28, 14/557), (30, 15/557), (9, 9/1114), (22, 11/557), (31, 31/1114), (16, 8/557), (5, 5/1114), (6, 3/557), (27, 27/1114), (10, 5/557), (25, 25/1114), (17, 17/1114), (26, 13/557), (33, 33/1114), (8, 4/557)]


### More on tuples and sequences in general

First, we can make an empty tuple like this:

In [137]:
empty = ()
len(empty)

0

Secondly, if we want a tuple with only one element we have to use a trailing comma.   If you think about it from the computer's point of view, if it can't see the trailing comma, how is it to tell that you want a tuple not just a single number?

In [138]:
aFineSingletonTuple = (1, )
type(aFineSingletonTuple)

<class 'tuple'>

In [139]:
unFineSingletonTuple = (1)
type(unFineSingletonTuple)

<class 'sage.rings.integer.Integer'>

In [140]:
unFineSingletonTuple = ((1))
type(unFineSingletonTuple)

<class 'sage.rings.integer.Integer'>

In [141]:
aFineSingletonTuple = ('lonelyString', )
type(aFineSingletonTuple)

<class 'tuple'>

In [142]:
unFineSingletonTuple = ('lonelyString')
type(unFineSingletonTuple)

<class 'str'>

You can make tuples out almost any object.   It's as easy as putting the things you want in ( ) parentheses and separating them by commas.  

In [143]:
myTupleOfStuff = (1, ZZ(1), QQ(1), RR(1), int(1), float(1))
myTupleOfStuff

(1, 1, 1, 1.00000000000000, 1, 1.0)

In [144]:
1==ZZ(1) # remember? will this be True/False?

True

Actually, you don't even need the ( ).   If you present SageMath (Python) with a sequence of object separated by commas, the default result is a tuple.

In [145]:
myTuple2 = 60, 400    # assign a tuple to the variable named myTuple2
type(myTuple2)

<class 'tuple'>

A statement like the one in the cell above is known as tuple packing (more generally, sequence packing).

When we work with tuples we also often use the opposite of packing - Python's very useful sequence unpacking capability.   This is, literally, taking a sequence and unpacking or extracting its elements.



In [146]:
x, y = myTuple2     # tuple unpacking
print( x)
print( y)
x * y

60
400


24000

The statement below is an example of *multiple assignment*, which you can see now is really just a combination of tuple packing followed by unpacking.

In [147]:
x, y = 600.0, 4000.0
print( x)
print( y)
x/y

600.000000000000
4000.00000000000


0.150000000000000

Let's try to implement a for loop with a tuple -- it will work just like the for loop with a list.

In [148]:
for x in (1,2,3):
    print( x^2)

1
4
9


Next let's try a list comprehension on the tuple. This creates a list as expected.

In [149]:
[x^2 for x in (1,2,3)]

[1, 4, 9]

But if we try the same comprehension with tuples, i.e., with `()` insteqad of `[]` we get a `generator object`. This will be covered next by first easing into functional programming in Python.

In [150]:
(x^2 for x in (1,2,3))

<generator object <genexpr> at 0x7fa8bd08a6d8>

## Functional Programming in Python

Let us take at the basics of functional programming and what Python has to offer on this front at:

- [https://docs.python.org/2/howto/functional.html#functional-programming-howto](https://docs.python.org/2/howto/functional.html#functional-programming-howto)

In [151]:
showURL("https://docs.python.org/3/howto/functional.html#functional-programming-howto",600)

### Iterators

From [https://docs.python.org/2/howto/functional.html#iterators](https://docs.python.org/2/howto/functional.html#iterators):

> An iterator is an object representing a stream of data; this object returns the data one element at a time. A Python iterator must support a method called next() that takes no arguments and always returns the next element of the stream. If there are no more elements in the stream, next() must raise the StopIteration exception. Iterators don’t have to be finite, though; it’s perfectly reasonable to write an iterator that produces an infinite stream of data.

> The built-in [iter()](https://docs.python.org/2/library/functions.html#iter) function takes an arbitrary object and tries to return an iterator that will return the object’s contents or elements, raising [TypeError](https://docs.python.org/2/library/exceptions.html#exceptions.TypeError) if the object doesn’t support iteration. Several of Python’s built-in data types support iteration, the most common being lists and dictionaries. An object is called an iterable object if you can get an iterator for it.

> You can experiment with the iteration interface manually:

In [152]:
L = [1,2,3]
it = iter(L)
it

In [153]:
type(it)

<class 'list_iterator'>

In [154]:
next(it)

1

In [155]:
next(it)

2

In [156]:
next(it)

3

In [158]:
next(it)

StopIteration: 

> Iterators can be materialized as lists or tuples by using the list() or tuple() constructor functions:

In [159]:
L = [1,2,3]
it = iter(L)
t = tuple(it)
t

(1, 2, 3)

In [160]:
L = [1,2,3]
it = iter(L)
l = list(it)
l

[1, 2, 3]

In [161]:
it = iter(L)
max(it)  # you can call functions on iterators

3

### Generators

"Naive Tuple Comprehension" creates a `generator` in SageMath/Python. From [https://docs.python.org/2/glossary.html#term-generator](https://docs.python.org/2/glossary.html#term-generator):

> **generator**
> A function which returns an iterator. It looks like a normal function except that it contains yield statements for producing a series of values usable in a for-loop or that can be retrieved one at a time with the next() function. Each yield temporarily suspends processing, remembering the location execution state (including local variables and pending try-statements). When the generator resumes, it picks-up where it left-off (in contrast to functions which start fresh on every invocation).

> **generator expression**
> An expression that returns an iterator. It looks like a normal expression followed by a for expression defining a loop variable, range, and an optional if expression. The combined expression generates values for an enclosing function:

**List comprehensions (listcomps) and Generator Expressions (genexps)** from 
- [https://docs.python.org/2/howto/functional.html#generator-expressions-and-list-comprehensions](https://docs.python.org/2/howto/functional.html#generator-expressions-and-list-comprehensions)

>With a list comprehension, you get back a Python list; stripped_list is a list containing the resulting lines, not an iterator. Generator expressions return an iterator that computes the values as necessary, not needing to materialize all the values at once. This means that list comprehensions aren’t useful if you’re working with iterators that return an infinite stream or a very large amount of data. Generator expressions are preferable in these situations.
> Generator expressions are surrounded by parentheses (“()”) and list comprehensions are surrounded by square brackets (“[]”). Generator expressions have the form:

```
( expression for expr in sequence1
             if condition1
             for expr2 in sequence2
             if condition2
             for expr3 in sequence3 ...
             if condition3
             for exprN in sequenceN
             if conditionN )
```

> Two common operations on an iterator’s output are 1) performing some operation for every element, 2) selecting a subset of elements that meet some condition. For example, given a list of strings, you might want to strip off trailing whitespace from each line or extract all the strings containing a given substring.

> List comprehensions and generator expressions (short form: “listcomps” and “genexps”) are a concise notation for such operations, borrowed from the functional programming language Haskell (https://www.haskell.org/). You can strip all the whitespace from a stream of strings with the following code:

In [162]:
line_list = ['  line 1\n', 'line 2  \n', 'line 3   \n']

# List comprehension -- returns list
stripped_list = [Line.strip() for Line in line_list]

# Generator expression -- returns a generator
stripped_iter = (Line.strip() for Line in line_list)

In [163]:
stripped_list # returns a list

['line 1', 'line 2', 'line 3']

In [164]:
type(stripped_iter) # returns a generator

<class 'generator'>

In [165]:
stripped_iter # returns only an genexpr generator object

<generator object <genexpr> at 0x7fa8bd08a408>

In [166]:
list(stripped_iter) # the generator can be materialized into a list 

['line 1', 'line 2', 'line 3']

In [167]:
tuple(stripped_iter) 
# the generator can be materialized into a tuple - it's already been emptied! 

()

In [168]:
# Generator expression -- returns a generator
stripped_iter = (Line.strip() for Line in line_list) # let's create a new generator
tuple(stripped_iter) # the generator can be materialized into a tuple now

('line 1', 'line 2', 'line 3')

Once again we have emptied the `stripped_iter` so we only get an empty list when we materilize it into a list.

In [169]:
list(stripped_iter) 

[]

In [170]:
showURL("https://docs.python.org/3/howto/functional.html#generator-expressions-and-list-comprehensions",500)

In [171]:
myGenerator = (x^2 for x in (1,2,3)) # this is actually a generator

In [172]:
type(myGenerator)

<class 'generator'>

In [173]:
next(myGenerator)

1

In [174]:
next(myGenerator)

4

In [175]:
next(myGenerator)

9

In [176]:
next(myGenerator)

StopIteration: 

We can pass a generator to a function like `sum` to evaluate it:

In [177]:
myGenerator = (i*i for i in range(10)) 

In [178]:
sum(myGenerator)

285

See [https://docs.python.org/2/howto/functional.html#generators](https://docs.python.org/2/howto/functional.html#generators) for more details:

> Generators are a special class of functions that simplify the task of writing iterators. Regular functions compute a value and return it, but generators return an iterator that returns a stream of values.

> You’re doubtless familiar with how regular function calls work in Python or C. When you call a function, it gets a private namespace where its local variables are created. When the function reaches a return statement, the local variables are destroyed and the value is returned to the caller. A later call to the same function creates a new private namespace and a fresh set of local variables. But, what if the local variables weren’t thrown away on exiting a function? What if you could later resume the function where it left off? This is what generators provide; they can be thought of as resumable functions.

> Here’s the simplest example of a generator function:

In [179]:
def generate_ints(N):
    for i in range(N):
        yield i

> Any function containing a yield keyword is a generator function; this is detected by Python’s [bytecode](https://docs.python.org/2/glossary.html#term-bytecode) compiler which compiles the function specially as a result.

> When you call a generator function, it doesn’t return a single value; instead it returns a generator object that supports the iterator protocol. On executing the yield expression, the generator outputs the value of i, similar to a return statement. The big difference between yield and a return statement is that on reaching a yield the generator’s state of execution is suspended and local variables are preserved. On the next call to the generator’s .next() method, the function will resume executing.

> Here’s a sample usage of the generate_ints() generator:

In [180]:
gen = generate_ints(3)
gen

<generator object generate_ints at 0x7fa8bd08ab10>

In [181]:
next(gen)

0

In [182]:
next(gen)

1

In [183]:
next(gen)

2

In [184]:
next(gen)

StopIteration: 

In [0]:
#gen. 
# see the methods available on gen by hitting TAB after the 'gen.' try to `close()` the generator

Using list comprehensions and generator expressions one can do functional programming in Python. But this is not the same as doing pure functional programming in a language such as haskell (see [https://www.haskell.org/](https://www.haskell.org/)) that is designed specifically for pure funcitonal programming.

In [ ]:
Arrays