## Modular arithmetic

Modular arithmetic (arithmetic modulo $m$) is a central theme in number theory and is crucial for generating random numbers from a computer (i.e., *machine-implementation of probabilistic objects*).  Being able to do this is essential for computational statistical experiments and methods that help do this are called Monte Carlo methods.  Such computer-generated random numbers are technically called *pseudo-random numbers*.

In this notebook we are going to learn to add and multiply modulo $m$ (this part of our notebook is adapted from William Stein's SageMath worksheet on Modular Arithmetic for the purposes of linear congruential generators).  If you want a more thorough treatment see [Modular Arithmetic](https://en.wikipedia.org/wiki/Modular_arithmetic) as displayed below.

In [3]:
showURL("https://en.wikipedia.org/wiki/Modular_arithmetic",500)

Remember when we talked about the modulus operator `%`?  The modulus operator gives the remainder after division:

In [4]:
14%12 # "14 modulo 12" or just "14 mod 12"

2

In [5]:
zeroto23Hours = range(0,24,1)  # 0,1,2...,23 hours in the 24-hours clock
print(list(zeroto23Hours))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


In [6]:
[x%12 for x in range(0,24,1)]  # x%12 for the 24 hours in the analog clock

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [7]:
set([x%12 for x in range(0,24,1)]) # unique hours 0,1,2,...,11 in analog clock by making a set out of the list

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}

Arithmetic modulo $m$ is like usual arithmetic, except every time you add or multiply, you also divide by $m$ and return the remainder.  For example, working modulo $m=12$, we have:

$$8 + 6 = 14 = 2$$

since $2$ is the remainder of the division of $14$ by $12$.  

Think of this as like the hours on a regular analog clock.  We already  do modular addition on a regular basis when we think about time, for example when answering the question:

Question: If it is 8pm now then what time will it be after I have spent the 6 hours that I am supposed to dedicate this week toward this course?  

Answer: 2am.

Modular addition and multiplication with numbers modulo $m$ is well defined, and has the following properties:

- $a + b = b+a$     (addition is commutative)
- $a \cdot b = b \cdot a$     (multiplication is commutative)
- $a\cdot (b + c) = a\cdot b + a\cdot c$    (multiplication is distributive over addition)
- If $a$ is coprime to $m$ (i.e., not divisible by any of the same primes), then there is a unique $b$ (mod $m$) such that $a\cdot b=1$.

Let us make a matrix of results from addition and multiplication modulo 4.

Before that realise that arithmetic over a set $\mathbb{M}$ is merely a function from the Cartesian product $\mathbb{M} \times \mathbb{M}$ of all pairs in $\mathbb{M}$ to $\mathbb{M}$:

$$
\star : \mathbb{M} \times \mathbb{M} \to \mathbb{M}
$$

where $\star$ is usually $+$ for "addition" or $*$ for "multiplication".

Thus, we can think of arithmetic as a set of three-tuples:
$$(x_1, x_2, x_3) \in \mathbb{M}^3 := \mathbb{M} \times \mathbb{M} \times \mathbb{M}, \quad \text{where} \quad x_3 = x_1 \star x_2. $$

In [8]:
mySageMatrix = matrix(2,3,[1, 2, 3, 4, 5, 6]) # this is how you make a 2X3 matrix in Sage
mySageMatrix

[1 2 3]
[4 5 6]

In [9]:
type(mySageMatrix) # the type says a lot

<class 'sage.matrix.matrix_integer_dense.Matrix_integer_dense'>

In [10]:
# uncomment next line and put cursor after . and hit Tab to see available methods
#mySageMatrix.

Let us list all the three-tuples for addition modulo 4 next.

In [11]:
m=4;
# list (i,j, (i+j) mod m) as (i,j) range in [0,1,2,3]
[(i,j,(i+j)%m) for i in range(m) for j in range(m)]

[(0, 0, 0),
 (0, 1, 1),
 (0, 2, 2),
 (0, 3, 3),
 (1, 0, 1),
 (1, 1, 2),
 (1, 2, 3),
 (1, 3, 0),
 (2, 0, 2),
 (2, 1, 3),
 (2, 2, 0),
 (2, 3, 1),
 (3, 0, 3),
 (3, 1, 0),
 (3, 2, 1),
 (3, 3, 2)]

In [12]:
[(i+j)%m for i in range(m) for j in range(m)] 
# just the third element of the three-tuple from above

[0, 1, 2, 3, 1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2]

Since the arguments to addition modulo m are fixed in a square array $[0,1,2\ldots,m-1]\times[0,1,2\ldots,m-1]$ we can simply focus on the image of the arithmetic modulo $m$ operation and place it over the square array using the following matrix call:

In [13]:
#addition mod m
matrix(m,m,[(i+j)%m for i in range(m) for j in range(m)])

[0 1 2 3]
[1 2 3 0]
[2 3 0 1]
[3 0 1 2]

In [14]:
# multiplication mod m
matrix(m,m,[(i*j)%m for i in range(m) for j in range(m)])

[0 0 0 0]
[0 1 2 3]
[0 2 0 2]
[0 3 2 1]

### Visualize Modular Arithmetic
In the following interactive image (created by William Stein) we make an addition and multiplication table modulo $m$, where you can control $m$ with the slider.   Try changing $m$ and seeing what effect it has:

In [15]:
import matplotlib.cm
cmaps = ['gray'] + list(sorted(matplotlib.cm.datad.keys()))

@interact
def mult_table(m=(4,(1..200)), cmap=("Color Map",cmaps)):
    Add = matrix(m,m,[(i+j)%m for i in range(m) for j in range(m)])
    Mult = matrix(m,m,[(i*j)%m for i in range(m) for j in range(m)])
    print ("Addition and multiplication table modulo %s"%m)
    show(graphics_array( (plot(Add, frame=True, xmin=-0.5, ymin=-0.5, xmax=m-0.5, ymax=m-0.5, cmap=cmap),\
						  plot(Mult,frame=True, xmin=-0.5, ymin=-0.5, xmax=m-0.5, ymax=m-0.5,cmap=cmap))))

Interactive function <function mult_table at 0x7f1b3e094e18> with 2 widgets
  m: SelectionSlider(description='…

Look at this for a while.  Make $m$ close to 200 slowly and see how the outputs of the two arithmetic operations change.

Answer the following questions (which refer to the default colour map) to be sure you understand the table:

- Question: Why is the top row and leftmost column of the multiplication table always black?
- Question: Why is there an anti-diagonal block line in the addition table (the left-most table)?
- Question: Why are the two halves of each table (the two pictures) symmetric about the diagonal?

You can change the colour map if you want to.

#### YouTry

You should be able to understand a bit of what is happening here.  See that there are two list comprehensions in there.  Take the line `matrix(m,m,[(i+j)%m for i in range(m) for j in range(m)])`.  The list comprehension part is `[(i+j)%m for i in range(m) for j in range(m)]`.  Let's pull it out and have a look at it.  We have set the default modulo `m` to `4` but you could change it if you want to:

In [16]:
m = 4
listFormAdd = [(i+j)%m for i in range(m) for j in range(m)]
listFormAdd

[0, 1, 2, 3, 1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2]

This list comprehension doing double duty:  remember that a list comprehension is like a short form for a for loop to create a list?  This one is like a short form for one for-loop nested within another for-loop.  

We could re-create what is going on here by making the same list with two for-loops.  This one uses modulo `m = 4` again.

In [17]:
m = 4
listFormAddTheHardWay = []
for i in range(m):
    for j in range(m):
        listFormAddTheHardWay.append((i+j)%m)
listFormAddTheHardWay

[0, 1, 2, 3, 1, 2, 3, 0, 2, 3, 0, 1, 3, 0, 1, 2]

Notice that the last statement in the list comprehension, `for j in range(m)`, is the inner loop in the nested for-loop.

The next step that Stein's  interactive image is to make a `matrix` out of the `list`.   We won't be doing matrices in detail in this course (we decided to concentrate on `numpy.arrays` and multi-dimensional `numpy.ndarrays` with floating-point numbers for numerical computing instead), but if you are interested, this statement uses the `matrix` function to make a `matrix` out of the `list` named `listFormAdd`.  The dimensions of the matrix are given by the first two arguments to the `matrix` function: `(m, m,...)`. 

In [18]:
matrixForm = matrix(m,m, listFormAdd)
matrixForm

[0 1 2 3]
[1 2 3 0]
[2 3 0 1]
[3 0 1 2]

Optionally, you can find out more about matrices from the documentation.

In [19]:
#uncomment and evaluate next line for doc
#?matrix

#### YouTry
Try recreating the matrix for multiplication, just as we have just recreated the one for addition.

In [20]:
m = 4
listFormMultiply = [] # make the list non-empty!

In [21]:
listFormMultiply

[]

### Modular arithmetic in SageMath

The simplest way to create a number modulo $m$ in Sage is to use the Mod(a,m) command.  We illustrate this below.

In [22]:
Mod(8, 12)

8

Let's assign it to a variable so that we can explore it further:

In [23]:
myModInt = Mod(8, 12)
myModInt

8

In [24]:
type(myModInt)

<class 'sage.rings.finite_rings.integer_mod.IntegerMod_int'>

In [25]:
parent(myModInt)

Ring of integers modulo 12

We will compare myModInt to a "normal" SageMath integer:

In [26]:
myInt = 8
myInt

8

In [27]:
type(myInt)

<class 'sage.rings.integer.Integer'>

In [28]:
parent(myInt) # ZZ

Integer Ring

We can see that `myModInt` and `myInt` are different types, but what does this mean?  How do they behave? 

Try addition:

In [29]:
myModInt + 6

2

In [30]:
myInt + 6

14

Was this what you already expected?

What about multiplication?

In [31]:
myModInt * 6

0

In [32]:
myInt * 6

48

What's going on here?  As we said above, arithmetic modulo mm is like usual arithmetic, except every time you add or multiply, you also divide by mm and return the remainder.  8 x 6 is 48, and the remainder of 48 divided by 12 (12 is our modulo) is 0. 

What about this one? What's happening here? 

In [33]:
Mod(-36,2020) # Benny was born in the year

1984

In [34]:
Mod(-1,12)  # what's an hour before mid-night

11

### YouTry
Can you create the number giving your year of birth (±1 year) in a similar way. For example, if you are 19 years old now then find the number -19 modulo 2018.



Let us assign 10 modulo 12 to a variable named `now`:

In [35]:
now = Mod(10, 12)
now

10

<img src="images/Week6NowEquals10.png" width=200>

#### YouTrys

Add -1 to `now`: <img src="images/Week6NowEquals9.png" width=200>

Put in the expression to do this in SageMath into the cell below:


And subtract 13 from the previous expression.  <img src="images/Week6NowEquals8.png" width=250>

Put in the expression to do this in SageMath into the cell below:

Also try adding 14 to the previous expression -- the new postition is not shown on this clock but you should be able to see what it should be.  


<img src="images/Week6NowWas8.png" width=200>

Put in the expression to do this in SageMath into the cell below:
    

And multiplying 2 by `now` (or `now` by 2)

Try making and using some modular integers of your own. Make sure that you can predict the results of simple addition and multiplication operations on them: this will confirm that you understand what's happening. 

#### YouTry Later!
What happens if you try arithmetic with two modular integers?  Does it matter if the moduli of both operands a and b in say a+b are the same if a and b are both modular integers?  Does this make sense to you?

(end of YouTrys)

---

---